apiVersion: apps/v1
kind: Deployment
metadata:
  name: farmshop-microservice
  labels:
    app: farmshop-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: farmshop-microservice
  template:
    metadata:
      labels:
        app: farmshop-microservice
    spec:
      containers:
      - name: farmshop-microservice
        image: farmshop-microservice:latest
        ports:
        - containerPort: 3002
        env:
        - name: BACKEND_URL
          value: "http://farmshop-backend-service"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: database-url
        resources:
          limits:
            cpu: "300m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: farmshop-microservice-service
spec:
  selector:
    app: farmshop-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
  type: ClusterIP